CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'operator');
CREATE TABLE sessions(token TEXT PRIMARY KEY, user_id INTEGER REFERENCES users(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE engagements(id INTEGER PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE members(engagement_id INTEGER REFERENCES engagements(id), user_id INTEGER REFERENCES users(id), PRIMARY KEY(engagement_id,user_id));
CREATE TABLE imports(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), filename TEXT NOT NULL, sha256 TEXT NOT NULL, format TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'queued', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, finished_at TEXT, warnings TEXT NOT NULL DEFAULT '[]', metadata TEXT NOT NULL DEFAULT '{}', record_count INTEGER DEFAULT 0, actor TEXT NOT NULL, UNIQUE(engagement_id,sha256));
CREATE TABLE assets(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), kind TEXT NOT NULL, value TEXT NOT NULL, domain TEXT NOT NULL DEFAULT '', country TEXT NOT NULL DEFAULT 'Unknown', city TEXT DEFAULT '', latitude REAL, longitude REAL, asn TEXT DEFAULT '', provider TEXT DEFAULT '', geo_source TEXT DEFAULT '', tags TEXT DEFAULT '', notes TEXT DEFAULT '', UNIQUE(engagement_id,kind,value));
CREATE INDEX asset_search ON assets(engagement_id,kind,domain,country);
CREATE TABLE records(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), import_id INTEGER REFERENCES imports(id), kind TEXT NOT NULL, title TEXT NOT NULL, observed_at TEXT, fields TEXT NOT NULL, raw TEXT NOT NULL, locator TEXT NOT NULL);
CREATE INDEX record_import ON records(import_id);
CREATE TABLE record_assets(record_id INTEGER REFERENCES records(id), asset_id INTEGER REFERENCES assets(id), PRIMARY KEY(record_id,asset_id));
CREATE INDEX record_asset_asset ON record_assets(asset_id,record_id);
CREATE TABLE relationships(id INTEGER PRIMARY KEY, source_id INTEGER REFERENCES assets(id), target_id INTEGER REFERENCES assets(id), kind TEXT NOT NULL, record_id INTEGER REFERENCES records(id), UNIQUE(source_id,target_id,kind,record_id));
CREATE INDEX relationships_source ON relationships(source_id);
CREATE INDEX relationships_target ON relationships(target_id);
CREATE TABLE endpoints(id INTEGER PRIMARY KEY, asset_id INTEGER REFERENCES assets(id), port INTEGER NOT NULL, protocol TEXT NOT NULL, UNIQUE(asset_id,port,protocol));
CREATE TABLE observations(id INTEGER PRIMARY KEY, endpoint_id INTEGER REFERENCES endpoints(id), record_id INTEGER REFERENCES records(id), state TEXT NOT NULL DEFAULT 'unknown', service TEXT NOT NULL DEFAULT '', evidence TEXT NOT NULL DEFAULT 'hint', product TEXT NOT NULL DEFAULT '', observed_at TEXT);
CREATE INDEX observation_endpoint ON observations(endpoint_id,observed_at);
CREATE TABLE interests(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), title TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'lead', priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'new', confirmed INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '', evidence TEXT NOT NULL DEFAULT '[]', asset_ids TEXT NOT NULL DEFAULT '[]', actor TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE scope_rules(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), action TEXT NOT NULL, target TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '');
CREATE TABLE saved_views(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), name TEXT NOT NULL, filters TEXT NOT NULL);
CREATE TABLE jobs(id INTEGER PRIMARY KEY, engagement_id INTEGER REFERENCES engagements(id), profile TEXT NOT NULL, actor TEXT NOT NULL, command TEXT NOT NULL, targets TEXT NOT NULL, excluded TEXT NOT NULL DEFAULT '[]', config TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'queued', created_at TEXT NOT NULL, started_at TEXT, ended_at TEXT, exit_code INTEGER, tool_version TEXT DEFAULT '', error TEXT DEFAULT '', cancel_requested INTEGER NOT NULL DEFAULT 0, import_ids TEXT DEFAULT '[]');
CREATE TABLE audit(id INTEGER PRIMARY KEY, engagement_id INTEGER, actor TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
